server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/photogram?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create로 하면 재실행할때마다 새로, none, update도 있음
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
      
  servlet:
    multipart: #멀티파트 타입 파일을 받겠다, 최대 사이즈 2mb
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234   

file: #이경로에 저장하겠다
  path: C:/workspace/springboot/upload/
